services:
  app:
    build:
      dockerfile: ./Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn mysite.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles
    networks:
      - my_network

  nginx:
      image: nginx:1.27.4
      ports:
        - "80:80"
      depends_on:
        - app
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        - static_volume:/app/staticfiles
      networks:
        - my_network

networks:
  my_network:
    driver: bridge

volumes:
  static_volume: